version: '3'
services:
  zookeeper:
    image: zookeeper:3.7
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA://kafka:9093,OUTSIDE_KAFKA://localhost:9092
      KAFKA_LISTENERS: INSIDE_KAFKA://0.0.0.0:9093,OUTSIDE_KAFKA://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_KAFKA:PLAINTEXT,OUTSIDE_KAFKA:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE_KAFKA: INSIDE_KAFKA
      KAFKA_LISTENER_NAME_OUTSIDE_KAFKA: OUTSIDE_KAFKA
      KAFKA_LISTENER_PORT_INSIDE_KAFKA: 9093
      KAFKA_LISTENER_PORT_OUTSIDE_KAFKA: 9092
      KAFKA_LISTENER_HOSTNAME_INSIDE_KAFKA: kafka
      KAFKA_LISTENER_HOSTNAME_OUTSIDE_KAFKA: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_KAFKA  # Adiciona essa linha
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
